# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Justin Dorfman | Open Source Sustainer"
# email: your-email@example.comm
version_number: '3.4.1'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.justindorfman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jdorfman
github_username:  jdorfman

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
   # - vendor/bundle/
   # - vendor/cache/
   # - vendor/gems/
   # - vendor/ruby/
