title: "Justin Dorfman | Open Source Sustainer"
version_number: '3.6.8'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.justindorfman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jdorfman
github_username:  jdorfman

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules